### ISSUE TITLE
Lightctl doesn't change brightness, brightnessctl does work

### ISSUE THREAD

**Issue by shotor** [misterdanb/avizo#17]
When I run lightctl the brightness never changes. The overlay is shown.

```sh
lightctl raise
lightctl lower
```

But when I use brightnessctl it does work, but doesn't show the overlay of course.

```sh
brightnessctl s +5%
brightnessctl s 5%-
```

Any way I can debug this? Or have avizo listen to brightnessctl instead?

Running arch on a frame.work laptop

**Comment by jirutka** [comment]
At the time you opened this MR, `lightctl` was only using [light](https://github.com/haikarainen/light), not [brightnessctl](https://github.com/Hummer12007/brightnessctl). Maybe you don’t have `light` installed?

Anyway, since today `lightctl` supports both `light` and `brightnessctl` (see #24), so it should work for you now.
