### ISSUE TITLE
Option to draw to all monitors

### ISSUE THREAD

**Issue by jeffmakes** [misterdanb/avizo#4]
Hi

Thanks for this great tool - looks great out of the box and easy to set up. I'm using it with Sway.

It would be great if I could pass an option to avizo to get it to draw to all monitors simultaneously in a multi output configuration. 

Often I adjust the system volume while looking at an unfocused monitor. For example, I could have my music player open on desktop 1, and I'm working on desktop 2, but I glance at 1 to see what's playing and adjust the volume with the keyboard. Since the focus is on 2, avizo opens over there, but I don't notice it because I'm looking at the unfocused monitor!

I had a quick look at the code but since I've never done anything with Vala or GTK I didn't get very far! 

Hope that makes some sense.

Cheers
Jeff

**Comment by misterdanb** [comment]
Hi Jeff,

I unterstand the situation and indeed that would be a nice feature.
On the technical side, since this is implemented with a UI toolkit and not on the Wayland level, one needs to open another window and — and here it maybe becomes interesting — instruct the compositor/Wayland to use a certain monitor for opening this window. In the best case there are option within GTK/GDK to to that.

I will have a look at (hopefully somewhat soonish) and see if it's possible the easy way.

Thanks for the suggestion!
danb

**Comment by jeffmakes** [comment]
I see well thanks for the response, danb, and for taking a look sometime.

Jeff

**Comment by jirutka** [comment]
@jeffmakes, I implemented this in #19.

**Comment by jeffmakes** [comment]
Great Jakub, thanks for letting me know!
